name: Bump Staging

on: workflow_dispatch

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: git setting
        run: |
          git config --local user.email "test@test.com"
          git config --local user.name "testkun"
      - name: Push Staging Branch
        run: |
          git branch
          git branch -D staging && git checkout -b staging
          git push origin staging -f
